### PR TITLE
fix: splitting multiline variables

### PR DESCRIPTION
**Pull request by ChezzyDerp**

### CODE REVIEW

**Comment by nikolaymatrosov** [comment]
Could you please provide a detailed explanation of your proposal, along with the test cases that demonstrate the issues you are aiming to resolve? Additionally, I would appreciate clarification on how this change will ensure the integrity of the existing configurations.

**Comment by ChezzyDerp** [comment]
> Could you please provide a detailed explanation of your proposal, along with the test cases that demonstrate the issues you are aiming to resolve? Additionally, I would appreciate clarification on how this change will ensure the integrity of the existing configurations.

Hi, I encountered an issue while using an ENV variable formatted as "some_key=base_64_encoded_data_with_equal_at_end=="

During the use of an ENV variable containing an = at the end, the string is incorrectly split, resulting in values like [key, ...value] = ['some_key', 'base_64_encoded_data_with_equal_at_end', '', '']. Consequently, value.join() outputs "base_64_encoded_data_with_equal_at_end,," with two commas at the end of the string instead of the expected equals sign.

**Comment by nikolaymatrosov** [comment]
That was my initial assumption as well, and **I agree that the current behavior is not correct**. 

However, I strongly recommend adding tests to cover the proposed changes, as it is not as straightforward as it may seem. In fact, I had to refer to the documentation on `String.split` behavior to ensure everything would function correctly. To prevent potential issues with this feature in the future, relevant tests are essential, and **the pull request will not be accepted without them**.

**Comment by ChezzyDerp** [comment]
> That was my initial assumption as well, and **I agree that the current behavior is not correct**.
> 
> However, I strongly recommend adding tests to cover the proposed changes, as it is not as straightforward as it may seem. In fact, I had to refer to the documentation on `String.split` behavior to ensure everything would function correctly. To prevent potential issues with this feature in the future, relevant tests are essential, and **the pull request will not be accepted without them**.

I added some cases to check validity of parseEnvironmentVariables

**Pull request merged**
